---

name: Run
on:
  schedule:
  - cron: '0 * * * *'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: npm ci
    - run: npm run start
      env:
        GARMIN_MAIL_ADDRESS: ${{ secrets.GARMIN_MAIL_ADDRESS }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        SLACK_LEGACY_TOKEN: ${{ secrets.SLACK_LEGACY_TOKEN }}
        EMOJIS: ${{ secrets.EMOJIS }}
        CI: 1
